version: '3.9'

services:
  mlops-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-backend
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
      - ELASTICSEARCH_HOST=http://elasticsearch:9200  # ELK 서버 주소
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: unless-stopped
    # Filebeat는 필요시 별도 추가

# 네트워크는 별도로 지정하지 않아도 단일 서버 내에서는 bridge 사용
