# MLOps/docker-compose.yml - version 라인 제거
# version: '3.9'  # 이 라인 삭제

services:
  mlops-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-backend
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
      - ELASTICSEARCH_HOST=http://elk-api:9201  # ELK API 포트로 수정
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # 볼륨 매핑 수정
    restart: unless-stopped
    networks:
      - mlops-network

networks:
  mlops-network:
    external: true
