services:
  mlops-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-backend
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
      - ELASTICSEARCH_HOST=http://15.164.50.188:9201
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - mlops-network

networks:
  mlops-network: