version: '3.9'
services:
  elasticsearch-init:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: elasticsearch-init
    user: "0"
    command: >
      bash -c "
        if [ ! -d /usr/share/elasticsearch/plugins/analysis-nori ]; then
          elasticsearch-plugin install analysis-nori --batch
        fi
      "
    volumes:
      - es-plugins:/usr/share/elasticsearch/plugins

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - es-plugins:/usr/share/elasticsearch/plugins
    ports:
      - ${ES_PORT}:9200
    networks:
      - mlops-network
    depends_on:
      elasticsearch-init:
        condition: service_completed_successfully

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
      - xpack.encryptedSavedObjects.encryptionKey=a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - elasticsearch
    networks:
      - mlops-network

  elk-api:
    build: .
    container_name: elk-api
    ports:
      - "9201:9201"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      - elasticsearch
    networks:
      - mlops-network

volumes:
  es-plugins:

networks:
  mlops-network:
    driver: bridge
    external: true