name: Deploy to EC2 (MLOps)

on:
  push:
    branches: [main]
    paths:
      - 'MLOps/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      with:
        host: ${{ secrets.EC2_HOST_ML }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        envs: OPENAI_KEY
        script: |
          # 프로젝트 디렉터리로 이동
          cd ~/MLOps
          
          # 최신 코드 받기
          git pull origin main
          dvc pull
          
          # MLOps 디렉터리로 이동
          cd MLOps
          
          # Docker 컨테이너 재시작 (docker-compose가 있다면)
          docker compose down -v || true
          docker compose up -d --build
          
          echo "Deployment completed successfully!"
