name: Deploy ELK To EC2

on:
    push:
        branches:
            - main
        paths:
            - ELK/**

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Github Repo Checkout
              uses: actions/checkout@v4

            - name: Connect To EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST_DB }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}

                  script: |
                      # 1. Git Repo 디렉토리 이동
                      cd ~/MLOps

                      # 2. 코드 최신화
                      git pull origin main

                      # 3. .env 파일 생성 및 docker compose 실행
                      cd ./ELK
                      echo "ES_HOST=${{ secrets.ES_HOST }}" > .env
                      echo "ES_PORT=${{ secrets.ES_PORT }}" >> .env
                      
                      docker compose stop elasticsearch-init elasticsearch kibana elk-api || true
                      docker compose rm -f elasticsearch-init elasticsearch kibana elk-api || true
                      docker compose up -d --build
